### ISSUE TITLE
Penultimate Checkpoint: 25 Pages (Amare)

### ISSUE THREAD

**Issue by jonathanhuydieu** [jonathanhuydieu/senior-design#20]
# Overview
Go ahead and close out this issue by commenting on it with a link to your pages once you've hit that 25 page mark! >:)

**Due Date: Wednesday, November 30, 2022**

**Comment by aamare1001** [comment]
Currently at 20, should be closer to 25 with more results form the survey. Planning to finish my 30 by Friday night because I'll be in Miami Saturday/Sunday for a Japanese exam. Will be here on Monday tho definitely.

**Comment by aamare1001** [comment]
24! Had to stop to go over some stuff for the interview but I'm really aiming to be done by Friday! will keep updated :D
